spring:
  datasource:
    base_url: jdbc:mysql://sandboxdb.interop.community:3306
    username: system
    password: ENC(eu7PppbSk0mHHUZjmjzZxPeU8X9aCckJ)
api_endpoint_index:
  prev:
    apiBaseURL_dstu2: https://api-v5-dstu2.interop.community
    apiBaseURL_stu3: https://api-v5-stu3.interop.community
    apiBaseURL_r4: https://api-v5-r4.interop.community
    apiBaseURL_r5:
  current:
    apiBaseURL_dstu2: https://api-v8-dstu2.interop.community
    apiBaseURL_stu3: https://api-v8-stu3.interop.community
    apiBaseURL_r4: https://api-v8-r4.interop.community
    apiBaseURL_r5: https://api-v8-r5.interop.community

api_url: https://api.interop.community