spring:
  datasource:
    base_url: jdbc:mysql://${DB_HOST:localhost}:${DB_PORT:3306}
    username: ${DB_USER}
    password: ${DB_PASSWORD}
api_endpoint_index:
  prev:
    apiBaseURL_dstu2: localhost
    apiBaseURL_stu3: localhost
    apiBaseURL_r4: localhost
    apiBaseURL_r5: localhost
  current:
    apiBaseURL_dstu2: ${API_DSTU2_HOST}
    apiBaseURL_stu3: ${API_STU3_HOST}
    apiBaseURL_r4: ${API_R4_HOST}
    apiBaseURL_r5: ${API_R5_HOST}

api_url: ${GATEWAY_URL}