spring:
  datasource:
    base_url: jdbc:mysql://sandboxdb.hspconsortium.org:3306
    username: system
    password: ENC(lA/Ifn1Cm6pYGGydIXNQIa6n7ryn5A1+)
api_endpoint_index:
  prev:
    apiBaseURL_dstu2: https://api-v5-dstu2.logicahealth.org
    apiBaseURL_stu3: https://api-v5-stu3.logicahealth.org
    apiBaseURL_r4: https://api-v5-r4.logicahealth.org
  current:
    apiBaseURL_dstu2: https://api-v8-dstu2.logicahealth.org
    apiBaseURL_stu3: https://api-v8-stu3.logicahealth.org
    apiBaseURL_r4: https://api-v8-r4.logicahealth.org

api_url: https://api.logicahealth.org