server:
  port: 12100
  tomcat:
    remote_ip_header: x-forwarded-for
    protocol_header: x-forwarded-proto
spring:
  cloud:
    gateway:
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins: "*"
            allowedMethods: "*"
  datasource:
    base_url: jdbc:mysql://${DB_HOST:localhost}:${DB_PORT:3306}
    my_schema: ${DB_NAME:sandman}
    url: ${spring.datasource.base_url}/${spring.datasource.my_schema}
    username: ${DB_USER:root}
    password: ${DB_PASSWORD:password}
    driverClassName: com.mysql.jdbc.Driver
    validation-query: SELECT 1
    test-on-borrow: true
    tomcat:
      initialSize: 1
      maxActive: 5
  jpa:
    show-sql: false
    hibernate:
      ddl-auto: validate
      dialect: org.hibernate.dialect.MySQL5InnoDBDialect
      naming_strategy: org.hibernate.cfg.ImprovedNamingStrategy
jasypt:
  encryptor:
    algorithm: PBEWithMD5AndTripleDES
api_endpoint_index:
  prev:
    dstu2: 5
    stu3: 6
    r4: 7
    apiBaseURL_dstu2: http://${API_DSTU2_HOST:localhost}:${API_DSTU2_PORT:8075}
    apiBaseURL_stu3: http://${API_STU3_HOST:localhost}:${API_STU3_PORT:8076}
    apiBaseURL_r4: http://${API_R4_HOST:localhost}:${API_R4_PORT:8077}
  current:
    dstu2: 8
    stu3: 9
    r4: 10
    apiBaseURL_dstu2: http://${API_DSTU2_HOST:localhost}:${API_DSTU2_PORT:8078}
    apiBaseURL_stu3: http://${API_STU3_HOST:localhost}:${API_STU3_PORT:8079}
    apiBaseURL_r4: http://${API_R4_HOST:localhost}:${API_R4_PORT:8070}

api_url: http://localhost:12100
